### ISSUE TITLE
Bug when adding a resource

### ISSUE THREAD

**Issue by ggornes** [HairdressingProject/HairdressingApp#29]
When trying to add an existing user, the error messages displays correctly.

But, if the message popup is closed or ignored, and the modal form closed, the error message box stays when opening the same or another modal.

The problem happens because the resources object stored on the state is updated with the errors, and closing the modal does not turn it back as it was before.

Also, this causes that the users table becomes empty, as there are no elements on resources.users.items

**Before trying to add an existing user**
![image](https://user-images.githubusercontent.com/42665819/82724151-9bf34f00-9d06-11ea-9521-879917363189.png)

**After trying to add an existing user**
![image](https://user-images.githubusercontent.com/42665819/82724161-b4636980-9d06-11ea-8846-b9eced1bc7c6.png)

**Comment by diego-cc** [comment]
Fixed by https://github.com/HairdressingProject/HairdressingApp/commit/e0aaa31ec00787a1db4dc7332a6dbb38ea2dced5
